baseURL = 'https://multi-vac.github.io/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'Lowkey-Hugo-Theme'
title = 'Mimesis'
enableRobotsTXT = true

# List Config
summaryLength = 15
paginate = 5

[markup.highlight]
      codeFences = false
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false
