[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "poems"
    name = "Poems"
    url = "/poems"
    weight = 3

[[main]]
    identifier = "now-reading"
    name = "Now Reading"
    url = "/now-reading"
    weight = 4

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 5

# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/multi-vac/"
    weight = 1


[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/multi_vac_/"
    weight = 2

[[social]]
    identifier = "goodreads"
    name = "Goodreads"
    url = "https://www.goodreads.com/user/show/59893490-ankit/"
    weight = 3
